// Source: https://es.wikipedia.org/wiki/ISO_3166-2
export const spanishCountryNames: Record<string, string> = {
  AD: "República de Adigueya",
  AL: "República de Altái",
  ALT: "Krai de Altái",
  AMU: "Óblast de Amur",
  ARK: "Óblast de Arcángel",
  AST: "Óblast de Astracán",
  BA: "República de Baskortostán",
  BEL: "Óblast de Bélgorod",
  BRY: "Óblast de Briansk",
  BU: "República de Buriatia",
  CE: "República de Chechenia",
  CHE: "Óblast de Cheliábinsk",
  CHU: "Distrito autónomo de Chukotka",
  CU: "República de Chuvasia",
  DA: "República de Daguestán",
  IN: "República de Ingusetia",
  IRK: "Óblast de Irkutsk",
  IVA: "Óblast de Ivánovo",
  KAM: "Krai de Kamchatka",
  KB: "República de Kabardia-Balkaria",
  KC: "República de Karacháyevo-Cherkesia",
  KDA: "Krai de Krasnodar",
  KEM: "Óblast de Kémerovo",
  KGD: "Óblast de Kaliningrado",
  KGN: "Óblast de Kurgán",
  KHA: "Krai de Jabárovsk",
  KHM: "Distrito autónomo Janti-Mansi",
  KIR: "Óblast de Kírov",
  KK: "República de Jakasia",
  KL: "República de Kalmukia",
  KLU: "Óblast de Kaluga",
  KO: "República de Komi",
  KOS: "Óblast de Kostromá",
  KR: "República de Carelia",
  KRS: "Óblast de Kursk",
  KYA: "Krai de Krasnoyarsk",
  LEN: "Óblast de Leningrado",
  LIP: "Óblast de Lípetsk",
  MAG: "Óblast de Magadán",
  ME: "República de Mari-El",
  MO: "República de Mordovia",
  MOS: "Óblast de Moscú",
  MOW: "Moscú",
  MUR: "Óblast de Múrmansk",
  NEN: "Distrito autónomo de Nenetsia",
  NGR: "Óblast de Nóvgorod",
  NIZ: "Óblast de Nizhni Nóvgorod",
  NVS: "Óblast de Novosibirsk",
  OMS: "Óblast de Omsk",
  ORE: "Óblast de Oremburgo",
  ORL: "Óblast de Oriol",
  PER: "Krai de Perm",
  PNZ: "Óblast de Penza",
  PRI: "Krai de Primorie",
  PSK: "Óblast de Pskov",
  ROS: "Óblast de Rostov",
  RYA: "Óblast de Riazán",
  SA: "República de Sajá",
  SAK: "Óblast de Sajalín",
  SAM: "Óblast de Samara",
  SAR: "Óblast de Sarátov",
  SE: "República de Osetia del Norte-Alania",
  SMO: "Óblast de Smolensk",
  SPE: "San Petersburgo",
  STA: "Krai de Stávropol",
  SVE: "Óblast de Sverdlovsk",
  TA: "República de Tartaristán",
  TAM: "Óblast de Tambov",
  TOM: "Óblast de Tomsk",
  TUL: "Óblast de Tula",
  TVE: "Óblast de Tver",
  TY: "República de Tuvá",
  TYU: "Óblast de Tiumén",
  UD: "República de Udmurtia",
  ULY: "Óblast de Uliánovsk",
  VGG: "Óblast de Volgogrado",
  VLA: "Óblast de Vladímir",
  VLG: "Óblast de Vólogda",
  VOR: "Óblast de Vorónezh",
  YAN: "Distrito autónomo de Yamalia-Nenetsia",
  YAR: "Óblast de Yaroslavl",
  YEV: "Óblast autónomo Hebreo",
  ZAB: "Krai de Zabaikalie",
};
