// Source: https://co.wikipedia.org/wiki/ISO_3166-2
export const catalanCountryNames: Record<string, string> = {
  AD: "República d'Adiguèsia",
  AL: "República de l'Altai",
  ALT: "Territori de l'Altai",
  AMU: "Província de l'Amur",
  ARK: "Província d'Arkhànguelsk",
  AST: "Província d'Àstrakhan",
  BA: "República de Baixkíria",
  BEL: "Província de Bélgorod",
  BRY: "Província de Briansk",
  BU: "República de Buriàtia",
  CE: "República de Txetxènia",
  CHE: "Província de Txeliàbinsk",
  CHU: "Districte autònom de Txukotka",
  CU: "República de Txuvàixia",
  DA: "República del Daguestan",
  IN: "República d'Ingúixia",
  IRK: "Província d'Irkutsk",
  IVA: "Província d'Ivànovo",
  KAM: "Territori de Kamtxatka",
  KB: "República de Kabardino-Balkària",
  KC: "República de Karatxai-Txerkèssia",
  KDA: "Territori de Krasnodar",
  KEM: "Província de Kémerovo",
  KGD: "Província de Kaliningrad",
  KGN: "Província de Kurgan",
  KHA: "Territori de Khabàrovsk",
  KHM: "Districte Autònom Khanti-Mansi — Iugrà",
  KIR: "Província de Kírov",
  KK: "República de Khakàssia",
  KL: "República de Calmúquia",
  KLU: "Província de Kaluga",
  KO: "República de Komi",
  KOS: "Província de Kostromà",
  KR: "República de Carèlia",
  KRS: "Província de Kursk",
  KYA: "Territori de Krasnoiarsk",
  LEN: "Província de Leningrad",
  LIP: "Província de Lípetsk",
  MAG: "Província de Magadan",
  ME: "República de Marí El",
  MO: "República de Mordòvia",
  MOS: "Província de Moscou",
  MOW: "Moscou",
  MUR: "Província de Múrmansk",
  NEN: "Nenètsia",
  NGR: "Província de Nóvgorod",
  NIZ: "Província de Nijni Nóvgorod",
  NVS: "Província de Novossibirsk",
  OMS: "Província d'Omsk",
  ORE: "Província d'Orenburg",
  ORL: "Província d'Oriol",
  PER: "Territori de Perm",
  PNZ: "Província de Penza",
  PRI: "Territori de Primórie",
  PSK: "Província de Pskov",
  ROS: "Província de Rostov",
  RYA: "Província de Riazan",
  SA: "República de Sakhà",
  SAK: "Província de Sakhalín",
  SAM: "Província de Samara",
  SAR: "Província de Saràtov",
  SE: "República d'Ossètia del Nord - Alània",
  SMO: "Província de Smolensk",
  SPE: "Sant Petersburg",
  STA: "Territori de Stàvropol",
  SVE: "Província de Sverdlovsk",
  TA: "República de Tatarstan",
  TAM: "Província de Tambov",
  TOM: "Província de Tomsk",
  TUL: "Província de Tula",
  TVE: "Província de Tver",
  TY: "República de Tuvà",
  TYU: "Província de Tiumén",
  UD: "República d'Udmúrtia",
  ULY: "Província d'Uliànovsk",
  VGG: "Província de Volgograd",
  VLA: "Província de Vladímir",
  VLG: "Província de Vólogda",
  VOR: "Província de Vorónej",
  YAN: "Districte Autònom Iamalo-Nenets",
  YAR: "Província de Iaroslavl",
  YEV: "Província Autònoma dels Hebreus",
  ZAB: "Territori de Zabaikal",
};
